---

apiVersion: v2
description: Full arr based setup for homelab
name: piratestack
version: 1.3.0
keywords:
  - sonarr
  - radarr
  - tautulli
  - overseerr
  - prowlarr
  - sabnzbd
  - bazarr
  - maintainerr
home: https://github.com/haijeploeg/charts/tree/main/charts/piratestack
maintainers:
  - name: haijeploeg
    email: ploeg.haije@gmail.com
 