---

apiVersion: v2
description: Movie organizer/manager for usenet and torrent users
name: sonarr
version: 1.0.0
keywords:
  - sonarr
home: https://github.com/haijeploeg/arr-helm/tree/main/charts/sonarr
icon: https://github.com/sonarr/sonarr/blob/develop/Logo/512.png
maintainers:
  - name: Haije Ploeg
    email: ploeg.haije@gmail.com
