---

image:
  tag: rolling
  pullPolicy: Always
  repository: ghcr.io/onedr0p/sonarr-develop

service:
  port: 8989
  type: ClusterIP

config:
  tz: Europe/Amsterdam
  # apikeySecret: sonarr-apikey

ingress:
  annotations: {}
  ingressClassName: nginx
  host: ""
  tls: []
  # - hosts:
  #   - sonarr.example.com
  #   secretName: sonarr-tls-secret

postgres:
  enabled: false
  #
  # Use classic values
  #
  # host: sonarr-postgres
  # port: 5432
  # user: sonarr
  # database: sonarr
  # password: P@ssw0rd123

  #
  # Use existing secret
  #
  # existingSecret: sonarr-postgres-secret
  # existingSecretHostKey: host
  # existingSecretPortKey: port
  # existingSecretUserKey: username
  # existingSecretDatabaseKey: dbname
  # existingSecretPasswordKey: password

resources:
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  statefulSet:
    runAsNonRoot: true
    runAsUser: 1057
    runAsGroup: 1057
    fsGroup: 1057
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [10000]
    seccompProfile:
      type: RuntimeDefault
  pod:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

storage:
  config:
    storage: 5Gi
  tv:
    nfs:
      path: ""
      server: ""
  downloads:
    nfs:
      path: ""
      server: ""

nodeSelector: {}

tolerations: []

affinity: {}
