---

image:
  tag: rolling
  pullPolicy: Always
  repository: ghcr.io/onedr0p/sabnzbd

service:
  port: 8080
  type: ClusterIP

config:
  tz: Europe/Amsterdam
  # apikeySecret: sabnzbd-apikey

ingress:
  annotations: {}
  ingressClassName: nginx
  host: ""
  tls: []
  # - hosts:
  #   - sabnzbd.example.com
  #   secretName: sabnzbd-tls-secret

resources:
  requests:
    cpu: "1"
    memory: 512Mi

securityContext:
  statefulSet:
    runAsNonRoot: true
    runAsUser: 1057
    runAsGroup: 1057
    fsGroup: 1057
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [10000]
    seccompProfile:
      type: RuntimeDefault
  pod:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

storage:
  config:
    storage: 5Gi
  downloads:
    nfs:
      path: ""
      server: ""

nodeSelector: {}

tolerations: []

affinity: {}
