{{- if and .Values.sabnzbd.enable .Values.sabnzbd.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: sabnzbd-httproute
  {{- with .Values.sabnzbd.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}
    {{- with .Values.sabnzbd.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.sabnzbd.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.sabnzbd.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: sabnzbd-service
          port: {{ .Values.sabnzbd.service.port }}
{{- end }}
