{{- if .Values.sabnzbd.enable }}

---

apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}
    {{- with .Values.sabnzbd.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sabnzbd.service.type }}
  ports:
    - port: {{ .Values.sabnzbd.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sabnzbd.selectorLabels" . | nindent 4 }}

{{- end }}