{{- if .Values.sonarr.enable }}

---

apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "sonarr.selectorLabels" . | nindent 4 }}
    {{- with .Values.sonarr.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sonarr.service.type }}
  ports:
    - port: {{ .Values.sonarr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sonarr.selectorLabels" . | nindent 4 }}

{{- end }}
