{{- if .Values.sonarr.enable }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "sonarr.selectorLabels" . | nindent 4 }}
    {{- with .Values.sonarr.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}
        {{- with .Values.sonarr.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
      {{- toYaml .Values.sonarr.securityContext.statefulSet | nindent 8 }}
      containers:
        - name: sonarr
          image: "{{ .Values.sonarr.image.repository }}:{{ .Values.sonarr.image.tag }}"
          imagePullPolicy: {{ .Values.sonarr.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.shared.config.tz | quote }}
            - name: PUID
              value: {{ .Values.shared.config.puid | quote }}
            - name: PGID
              value: {{ .Values.shared.config.pgid | quote }}
            {{- if .Values.sonarr.config.apikeySecret }}
            - name: SONARR__AUTH__APIKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sonarr.config.apikeySecret }}
                  key: apikey
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.sonarr.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.sonarr.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.sonarr.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.sonarr.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.sonarr.securityContext.pod | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          persistentVolumeClaim:
            claimName: sonarr-config
        - name: tv
          nfs:
            path: {{ .Values.shared.storage.tv.nfs.path }}
            server: {{ .Values.shared.storage.tv.nfs.server }}
        - name: downloads
          persistentVolumeClaim:
            claimName: piratestack-downloads
      {{- with .Values.sonarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sonarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sonarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
