{{- if .Values.tautulli.enable }}

---

apiVersion: v1
kind: Service
metadata:
  name: tautulli-service
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "tautulli.selectorLabels" . | nindent 4 }}
    {{- with .Values.tautulli.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.tautulli.service.type }}
  ports:
    - port: {{ .Values.tautulli.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tautulli.selectorLabels" . | nindent 4 }}

{{- end }}
