{{- if .Values.overseerr.enable }}

---

apiVersion: v1
kind: Service
metadata:
  name: overseerr-service
  labels:
    {{- include "piratestack.labels" . | nindent 4 }}
    {{- include "overseerr.selectorLabels" . | nindent 4 }}
    {{- with .Values.overseerr.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.overseerr.service.type }}
  ports:
    - port: {{ .Values.overseerr.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "overseerr.selectorLabels" . | nindent 4 }}

{{- end }}
