---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    {{- include "plex.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.nodePort.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Chart.Name }}-nodeport-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 32400
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort.port }}
