---

apiVersion: v2
description: A Helm chart for deploying the Plex Personal Media Server(PMS) server
name: plex
version: 1.0.6
keywords:
  - plex
home: https://github.com/haijeploeg/arr-helm/tree/main/charts/plex
icon: https://github.com/plexinc/pms-docker/blob/master/img/plex-server.png
maintainers:
  - name: haijeploeg
    email: ploeg.haije@gmail.com
