---

image:
  tag: latest
  pullPolicy: Always
  repository: lscr.io/linuxserver/plex

service:
  port: 32400
  type: ClusterIP
  nodePort:
    port: 32400
    # annotations:
    #   metallb.universe.tf/ip-allocated-from-pool: homelab-ip-pool
    #   metallb.universe.tf/loadBalancerIPs: 192.168.0.241

config:
  tz: Europe/Amsterdam

ingress:
  annotations: {}
  ingressClassName: nginx
  host: ""
  tls: []
  # - hosts:
  #   - plex.example.com
  #   secretName: plex-tls-secret

gpu:
  intel: false

resources: {}

securityContext:
  statefulSet: {}
  pod: {}

storage:
  config:
    storage: 5Gi
  tv:
    nfs:
      path: ""
      server: ""
  movies:
    nfs:
      path: ""
      server: ""

nodeSelector: {}

tolerations: []

affinity: {}
