---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarr.labels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
      {{- toYaml .Values.securityContext.statefulSet | nindent 8 }}
      containers:
        - name: sonarr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TZ
              value: {{ .Values.env.tz | quote }}
            {{- if .Values.postgres.enabled }}
            - name: SONARR__POSTGRES__HOST
              {{- if .Values.postgres.existingSecretHostKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postges.existingSecretHostKey }}
              {{- else }}
              value: {{ .Values.postgres.host }}
              {{- end }}
            - name: SONARR__POSTGRES__PORT
              {{- if .Values.postgres.existingSecretPortKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postges.existingSecretPortKey }}
              {{- else }}
              value: {{ .Values.postgres.port | quote }}
              {{- end }}
            - name: SONARR__POSTGRES__USER
              {{- if .Values.postgres.existingSecretUserKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postges.existingSecretUserKey }}
              {{- else }}
              value: {{ .Values.postgres.user }}
              {{- end }}
            - name: SONARR__POSTGRES__PASSWORD
              {{- if .Values.postgres.existingSecretPasswordKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postges.existingSecretPasswordKey }}
              {{- else }}
              value: {{ .Values.postgres.password }}
              {{- end }}
            - name: SONARR__POSTGRES__MAINDB
              {{- if .Values.postgres.existingSecretDatabaseKey }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: {{ .Values.postges.existingSecretDatabaseKey }}
              {{- else }}
              value: {{ .Values.postgres.database }}
              {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext.pod | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tv
              mountPath: /tv
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-config
        - name: tv
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-tv
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-downloads
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
