---

image:
  tag: rolling
  pullPolicy: Always
  repository: ghcr.io/onedr0p/radarr

service:
  port: 7878
  type: ClusterIP

env:
  puid: "65534"
  pgid: "65534"
  tz: Europe/Amsterdam

ingress:
  annotations: {}
  ingressClassName: nginx
  host: ""
  tls: []
  # - hosts:
  #   - radarr.example.com
  #   secretName: radarr-tls-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  fsGroup: 65534
  fsGroupChangePolicy: OnRootMismatch
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534

storage:
  config:
    storage: 5Gi
  movies:
    storage: 100Gi
    storageClassName: ""
    nfs:
      path: ""
      server: ""
  downloads:
    storage: 100Gi
    storageClassName: ""
    nfs:
      path: ""
      server: ""

nodeSelector: {}

tolerations: []

affinity: {}
