---

image:
  tag: rolling
  pullPolicy: Always
  repository: ghcr.io/onedr0p/prowlarr-develop

service:
  port: 9696
  type: ClusterIP

config:
  tz: Europe/Amsterdam
  # apikeySecret: prowlarr-apikey

ingress:
  annotations: {}
  ingressClassName: nginx
  host: ""
  tls: []
  # - hosts:
  #   - prowlarr.example.com
  #   secretName: prowlarr-tls-secret

postgres:
  enabled: false
  #
  # Use classic values
  #
  # host: prowlarr-postgres
  # port: 5432
  # user: prowlarr
  # database: prowlarr
  # password: P@ssw0rd123

  #
  # Use existing secret
  #
  # existingSecret: prowlarr-postgres-secret
  # existingSecretHostKey: host
  # existingSecretPortKey: port
  # existingSecretUserKey: username
  # existingSecretDatabaseKey: dbname
  # existingSecretPasswordKey: password

resources:
  requests:
    cpu: 100m
    memory: 128Mi

securityContext:
  statefulSet:
    runAsNonRoot: true
    runAsUser: 1057
    runAsGroup: 1057
    fsGroup: 1057
    fsGroupChangePolicy: OnRootMismatch
    supplementalGroups: [10000]
    seccompProfile:
      type: RuntimeDefault
  pod:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]

storage:
  config:
    storage: 5Gi

nodeSelector: {}

tolerations: []

affinity: {}
